In [3]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.5)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 24.4 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 44.5 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.5 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## 1. Lista de conceptos para la búsqueda

In [5]:
import pandas as pd
import numpy as np

# Crear dataframe
credicorp = pd.DataFrame({
    "CONCEPTOS": [
        "BCP",
        "Credicorp",
        "YAPE",
        "Mibanco",
        "Tarjeta IO",
        "Banco de Crédito",
        "Grupo Romero",
        "Tenpo",
        "Krealo"
    ],
    "INCLUIR": [
        "Perú",
        "Credicorp",
        "YAPE",
        "Mibanco",
        "Tarjeta IO",
        "Banco de Crédito",
        "Grupo Romero",
        "Tenpo",
        "Krealo"
    ]
})

print(credicorp)

          CONCEPTOS           INCLUIR
0               BCP              Perú
1         Credicorp         Credicorp
2              YAPE              YAPE
3           Mibanco           Mibanco
4        Tarjeta IO        Tarjeta IO
5  Banco de Crédito  Banco de Crédito
6      Grupo Romero      Grupo Romero
7             Tenpo             Tenpo
8            Krealo            Krealo

### Agregar comillas a cada valor PARA LA BUSQUEDA DEL NOMBRE COMPLETO

In [6]:
credicorp["CONCEPTOS"] = '"' + credicorp["CONCEPTOS"] + '"'
credicorp["INCLUIR"] = '"' + credicorp["INCLUIR"] + '"'

credicorp

            CONCEPTOS             INCLUIR
0               "BCP"              "Perú"
1         "Credicorp"         "Credicorp"
2              "YAPE"              "YAPE"
3           "Mibanco"           "Mibanco"
4        "Tarjeta IO"        "Tarjeta IO"
5  "Banco de Crédito"  "Banco de Crédito"
6      "Grupo Romero"      "Grupo Romero"
7             "Tenpo"             "Tenpo"
8            "Krealo"            "Krealo"

### Crear el diccionario para almacenar los resultados

In [7]:
diccionario = credicorp.to_dict(orient='records')

## 2. Búsqueda de noticias

In [8]:
!pip install feedparser

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (pyproject.toml) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6090 sha256=c629ed5ccbed83f56ba2460added585c8a90d64d49eb05b6fdfeae4ba0d15473
  Stored in directory: /home/codespace/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [feedparser]
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [9]:
import feedparser as fp
import pandas as pd
from urllib.parse import quote
from datetime import datetime

# URL del feed RSS de Google News
#rss_url = "https://news.google.com/rss?hl=es&gl=ES&ceid=ES:es"

def search_rss( CONCEPTOS,INCLUIR,start_date, results):
    n = results
    CONCEPTOS = CONCEPTOS
    INCLUIR = INCLUIR
    query = f'''{CONCEPTOS} AND {INCLUIR} '''
    
    # Parámetros de búsqueda
    encoded_query = quote(query)  
    # Codifica el texto para URLs
    rss_url = f"https://news.google.com/rss/search?q={encoded_query}&hl=es&gl=PE&ceid=PE:es"

    # Parsear el feed
    feed = fp.parse(rss_url)
    start_date = datetime.strptime(start_date, '%d/%m/%Y %H:%M:%S')

    # Filtrar las entradas usando comprensión de listas
    sorted_entries = sorted(
        (entry for entry in feed.entries if datetime.strptime(entry.published, '%a, %d %b %Y %H:%M:%S  %Z') > start_date),
        key=lambda entry: datetime.strptime(entry.published, '%a, %d %b %Y %H:%M:%S %Z'),
        reverse=True  # Si quieres ordenarlas de más reciente a más antiguo
    )
    
    top_n_entries = sorted_entries[:n]

    return top_n_entries
    
    #for entry in top_n_entries:
    #    print(entry.title, '\n', entry.published , '\n', '-'*80)

In [10]:
import random
import time 

results = 10 
contador = 0 
total_concepts = len(diccionario) 
start_date = '01/05/2026 00:00:00'

start_time = time.time()

# Aplicar la función search_rss
for entry in diccionario:
    contador += 1       
    CONCEPTOS = entry['CONCEPTOS'] 
    INCLUIR = entry['INCLUIR'] 
    # Llamar a search_rss
    entry['RSS'] = search_rss(CONCEPTOS,INCLUIR,  start_date, results) 
    
    print(f"\rEmpresa {contador} de {total_concepts}: {CONCEPTOS} analizada.{' ' * 100}", end="") 

end_time = time.time()
elapsed_time = end_time - start_time

mins, secs = divmod(elapsed_time, 60)
hours, mins = divmod(mins, 60)

print(f"\n⏱️ Tiempo: {int(hours)}h {int(mins)}m {secs:.2f}s")

Empresa 9 de 9: "Krealo" analizada.
⏱️ Tiempo: 0h 0m 5.61s

In [11]:
PALABRAS_EXCLUIR = [ "farandula", "espectaculos"]
rows = [] 

for entry in diccionario: 
    CONCEPTOS = entry["CONCEPTOS"] 
    
    for rss in entry["RSS"]: 

        titulo = rss["title"]
        link = rss["link"]
        
        # excluir noticias irrelevantes
        if any(palabra in titulo or palabra in link for palabra in PALABRAS_EXCLUIR):
            continue
            
        published = datetime.strptime(
            rss["published"],
            "%a, %d %b %Y %H:%M:%S %Z"
            ) 
        rows.append({ 
            "Concepts": CONCEPTOS, 
            "Title": rss["title"], 
            "Link": rss["link"], 
            "Published_date": published.strftime("%d/%m/%Y %H:%M:%S") 
        }) 
        
# Crear un DataFrame 
resultados_link_rss = pd.DataFrame(rows)

In [12]:
resultados_link_rss

,Concepts,Title,Link,Published_date
0,"""BCP""",CTS 2026: ¿Por qué no puedo retirar el pago y ...,https://news.google.com/rss/articles/CBMitgFBV...,15/05/2026 12:30:00
1,"""BCP""",Depósito CTS llega con retiro: ¿Cómo saber si ...,https://news.google.com/rss/articles/CBMiuAFBV...,13/05/2026 12:22:00
2,"""BCP""",Comparativa: tarjetas BCP vs Interbank vs BBVA...,https://news.google.com/rss/articles/CBMikAFBV...,12/05/2026 13:22:02
3,"""BCP""",Reportan caída de Yape y BCP en pleno Día de l...,https://news.google.com/rss/articles/CBMi-AFBV...,11/05/2026 01:34:01
4,"""BCP""",BCP: más de 7 millones de peruanos han sido in...,https://news.google.com/rss/articles/CBMi1gFBV...,08/05/2026 07:00:00
5,"""BCP""",BCP: SBS autoriza compra de banco en Estados U...,https://news.google.com/rss/articles/CBMi6wFBV...,08/05/2026 07:00:00
6,"""BCP""",IFC otorga financiamiento sostenible por US$25...,https://news.google.com/rss/articles/CBMiqwFBV...,06/05/2026 20:54:14
7,"""BCP""",BCP obtuvo la autorización de compra de banco ...,https://news.google.com/rss/articles/CBMiswFBV...,06/05/2026 14:00:24
8,"""BCP""",BCP obtiene autorización para comprar banco en...,https://news.google.com/rss/articles/CBMikwFBV...,06/05/2026 07:00:00
9,"""BCP""",SBS autoriza al BCP la adquisición de un banco...,https://news.google.com/rss/articles/CBMilwFBV...,06/05/2026 07:00:00
10,"""Credicorp""","“Perú parece un país europeo”, un análisis de ...",https://news.google.com/rss/articles/CBMi6AFBV...,16/05/2026 23:08:00
11,"""Credicorp""",Credicorp gana impulso en 1T26: utilidades sub...,https://news.google.com/rss/articles/CBMitAFBV...,16/05/2026 15:10:13
12,"""Credicorp""",Utilidad neta de Credicorp alcanzó los S/2.063...,https://news.google.com/rss/articles/CBMi1AFBV...,16/05/2026 01:57:29
13,"""Credicorp""",Utilidad neta de Credicorp aumentó 16.1% en el...,https://news.google.com/rss/articles/CBMi8AFBV...,15/05/2026 23:46:51
14,"""Credicorp""","Mibanco: el actual CFO de Credicorp, Alejandro...",https://news.google.com/rss/articles/CBMinwFBV...,14/05/2026 13:19:35
15,"""Credicorp""",Alejandro Pérez-Reyes es nombrado como nuevo g...,https://news.google.com/rss/articles/CBMiggJBV...,13/05/2026 23:49:30
16,"""Credicorp""",Credicorp anuncia cambios ejecutivos efectivos...,https://news.google.com/rss/articles/CBMivgFBV...,13/05/2026 20:42:00
17,"""Credicorp""",Credicorp designa a Alejandro Pérez-Reyes como...,https://news.google.com/rss/articles/CBMinwFBV...,13/05/2026 20:35:00
18,"""Credicorp""",Ingresos y utilidad de Credicorp Capital creci...,https://news.google.com/rss/articles/CBMimAFBV...,11/05/2026 23:40:00
19,"""Credicorp""",Resultados de empresas según el análisis de Cr...,https://news.google.com/rss/articles/CBMisAFBV...,11/05/2026 20:15:00
20,"""YAPE""",¿Ni Yape ni Plin? El recuento de todas las bil...,https://news.google.com/rss/articles/CBMibkFVX...,15/05/2026 23:08:35
21,"""YAPE""",¿Recibes pagos desde Yape o Plin? Toma nota - ...,https://news.google.com/rss/articles/CBMilAFBV...,15/05/2026 16:10:19
22,"""YAPE""",Yape sorprende con actualización: así serán ah...,https://news.google.com/rss/articles/CBMi0AFBV...,13/05/2026 22:26:00
23,"""YAPE""",Yape acelera su expansión regional habilitando...,https://news.google.com/rss/articles/CBMi7gFBV...,13/05/2026 16:43:52
24,"""YAPE""",Pepsi y Yape premian compras en Perú - America...,https://news.google.com/rss/articles/CBMiiAFBV...,12/05/2026 22:43:57
25,"""YAPE""",¿Tuviste problemas con Yape? Así puedes hacer ...,https://news.google.com/rss/articles/CBMiyAFBV...,11/05/2026 16:17:39
26,"""YAPE""",Reportan caída de Yape y BCP en pleno Día de l...,https://news.google.com/rss/articles/CBMi-AFBV...,11/05/2026 01:34:01
27,"""YAPE""",Yape y Plin podrían dejar de usarse para pagar...,https://news.google.com/rss/articles/CBMiqAFBV...,06/05/2026 07:00:00
28,"""YAPE""","Yape ya puede enviar dinero a Argentina, Chile...",https://news.google.com/rss/articles/CBMiwAFBV...,01/05/2026 07:00:00
29,"""Mibanco""",Mibanco ejecuta el primer desembolso 100% auto...,https://news.google.com/rss/articles/CBMiogFBV...,14/05/2026 18:36:00
30,"""Mibanco""","Mibanco: el actual CFO de Credicorp, Alejandro...",https://news.google.com/rss/articles/CBMinwFBV...,14/05/2026 13:19:35
31,"""Mibanco""",Alejandro Pérez-Reyes es nombrado como nuevo g...,https://news.google.com/rss/articles/CBMiggJBV...,13/05/2026 23:49:30
32,"""Mibanco""",Alejandro Pérez-Reyes fue elegido como gerente...,https://news.google.com/rss/articles/CBMimAFBV...,13/05/2026 23:38:17
33,"""Mibanco""",Alejandro Pérez-Reyes asumirá el puesto de ger...,https://news.google.com/rss/articles/CBMirAFBV...,13/05/2026 21:58:43
34,"""Mibanco""","Mibanco: el actual CFO de Credicorp, Alejandro...",https://news.google.com/rss/articles/CBMiwAFBV...,13/05/2026 20:41:29
35,"""Mibanco""",Mibanco dinamiza campaña por Día de la Madre e...,https://news.google.com/rss/articles/CBMi3gFBV...,05/05/2026 02:29:34
36,"""Tarjeta IO""",Tarjeta iO al servicio de Arequipa - DIARIO VIRAL,https://news.google.com/rss/articles/CBMiggFBV...,16/05/2026 06:00:21
37,"""Banco de Crédito""",Banco de Credito del Perú S A : Otros Hechos D...,https://news.google.com/rss/articles/CBMiygFBV...,14/05/2026 16:52:11
38,"""Banco de Crédito""",Banco de Crédito del Perú S.A. anuncia cambios...,https://news.google.com/rss/articles/CBMivgFBV...,13/05/2026 20:35:00
39,"""Banco de Crédito""",Banco de Credito del Perú S A : Otros Hechos D...,https://news.google.com/rss/articles/CBMi5wFBV...,13/05/2026 20:13:23
40,"""Banco de Crédito""",Tarjetas de crédito con cashback en Perú: cuál...,https://news.google.com/rss/articles/CBMimwFBV...,12/05/2026 13:11:13
41,"""Banco de Crédito""",La Junta General de Accionistas de Banco de Cr...,https://news.google.com/rss/articles/CBMi7gFBV...,07/05/2026 07:00:00
42,"""Banco de Crédito""",Le vaciaron su cuenta del BCP a un jubilado: c...,https://news.google.com/rss/articles/CBMiwgJBV...,02/05/2026 18:50:21
43,"""Banco de Crédito""",La Reserva Federal de Estados Unidos aprueba a...,https://news.google.com/rss/articles/CBMiwgFBV...,01/05/2026 07:00:00
44,"""Grupo Romero""",Exitosa Noticias. . 🔴🔵 #ExitosaTeEscucha 🎤 | L...,https://news.google.com/rss/articles/CBMi7AFBV...,07/05/2026 17:00:29
45,"""Grupo Romero""",Grupo Romero impulsa nuevo ciclo de Orygen con...,https://news.google.com/rss/articles/CBMitAFBV...,07/05/2026 00:38:23
46,"""Grupo Romero""",Energía renovable en Perú avanza con el proyec...,https://news.google.com/rss/articles/CBMivAFBV...,04/05/2026 07:00:00
47,"""Grupo Romero""",Fintech Tyba del Grupo Romero promueve fuga de...,https://news.google.com/rss/articles/CBMi0AFBV...,02/05/2026 17:14:37
48,"""Tenpo""",Tenpo prepara su ingreso a la ABIF y apuesta p...,https://news.google.com/rss/articles/CBMiuwFBV...,14/05/2026 12:03:51
49,"""Tenpo""","Tenpo: el primer neobanco que premia con ""misi...",https://news.google.com/rss/articles/CBMibEFVX...,06/05/2026 21:26:58

### Resumen de resultados

In [13]:
num_not= len(resultados_link_rss)
num_conc= resultados_link_rss['Concepts'].nunique() 

print(f"Hay {num_not} noticias correspondientes a {num_conc} conceptos")

Hay 50 noticias correspondientes a 8 conceptos

## 3. Transformación de URL

In [15]:
!pip install googlenewsdecoder

Requirement already satisfied: googlenewsdecoder in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.1.7)
Requirement already satisfied: requests>=2.32.3 in /home/codespace/.local/lib/python3.12/site-packages (from googlenewsdecoder) (2.32.5)
Requirement already satisfied: selectolax>=0.3.27 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from googlenewsdecoder) (0.4.9)
Requirement already satisfied: pysocks>=1.7.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from googlenewsdecoder) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.32.3->googlenewsdecoder) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.32.3->googlenewsdecoder) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.32.3->googlenewsdecoder) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.32.3->googlenewsdecoder) (2026.2.25)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [16]:
import time
from googlenewsdecoder import gnewsdecoder

start_time = time.time()


total_news = len(resultados_link_rss)
contador = 0

decoded_urls = []
for url in resultados_link_rss['Link']:
    contador+= 1
    try:
        decoded = gnewsdecoder(url, interval=1)['decoded_url']
    except Exception as e:
        decoded = None  # en caso de error
        print(f"Error con {url}: {e}")
    decoded_urls.append(decoded)
    time.sleep(2)  # <-- espera 1 segundo entre cada request

    # Imprimir el progreso y el nombre de la empresa
    print(f"\rNoticia {contador} de {total_news}:  analizada.{' ' * 100}", end="")
 
resultados_link_rss['URL'] = decoded_urls


end_time = time.time()
elapsed_time = end_time - start_time

mins, secs = divmod(elapsed_time, 60)
hours, mins = divmod(mins, 60)

print(f"\n⏱️ Tiempo total de ejecución: {int(hours)}h {int(mins)}m {secs:.2f}s")

Noticia 50 de 50:  analizada.
⏱️ Tiempo total de ejecución: 0h 3m 0.40s

In [19]:
resultados_link_rss.head(5)

,Concepts,Title,Link,Published_date,URL
0,"""BCP""",CTS 2026: ¿Por qué no puedo retirar el pago y ...,https://news.google.com/rss/articles/CBMitgFBV...,15/05/2026 12:30:00,https://www.infobae.com/peru/2026/05/14/cts-20...
1,"""BCP""",Depósito CTS llega con retiro: ¿Cómo saber si ...,https://news.google.com/rss/articles/CBMiuAFBV...,13/05/2026 12:22:00,https://www.infobae.com/peru/2026/05/12/deposi...
2,"""BCP""",Comparativa: tarjetas BCP vs Interbank vs BBVA...,https://news.google.com/rss/articles/CBMikAFBV...,12/05/2026 13:22:02,https://www.noticiasser.pe/comparativa-tarjeta...
3,"""BCP""",Reportan caída de Yape y BCP en pleno Día de l...,https://news.google.com/rss/articles/CBMi-AFBV...,11/05/2026 01:34:01,https://larepublica.pe/economia/2026/05/10/rep...
4,"""BCP""",BCP: más de 7 millones de peruanos han sido in...,https://news.google.com/rss/articles/CBMi1gFBV...,08/05/2026 07:00:00,https://elcomercio.pe/economia/peru/mas-de-7-m...